---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "copy backend file"
  become: true
  copy:
    src: /root/project/backend
    dest: /root
    force: no

- name: "install npm packages"
  become: true
  command: npm install --force
  args:
    chdir: /root/backend

- name: "compile npm packages"
  become: true
  command: npm run build
  args:
    chdir: /root/backend

- name: "start server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: /root/backend/dist